name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build macOS
      run: clang++ -std=c++17 test/main.mm -framework Cocoa

    - name: Build ios
      run: clang++ -std=c++17 -arch arm64 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -c test/main.mm

      
